### ISSUE TITLE
Cannot read property of null (performance hooks)

### ISSUE THREAD

**Issue by MattJustMatt** [serdnam/fastify-sentry#8]
Thank you so much for making this!

```[App] [21:26:16.942] ERROR (80076): request errored
[App]     reqId: "req-h"
[App]     res: {
[App]       "statusCode": 500
[App]     }
[App]     responseTime: 0.30369997024536133
[App]     err: {
[App]       "type": "TypeError",
[App]       "message": "Cannot read properties of null (reading 'onSend')",
[App]       "stack":
[App]           TypeError: Cannot read properties of null (reading 'onSend')
[App]               at C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\@serdnam+fastify-sentry@7.0.0\node_modules\@serdnam\fastify-sentry\dist\index.js:184:27
[App]               at Object.nextHookWithoutPayload (C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\@serdnam+fastify-sentry@7.0.0\node_modules\@serdnam\fastify-sentry\dist\index.js:201:32)
[App]               at onResponseIterator (C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\fastify@4.19.2\node_modules\fastify\lib\reply.js:775:10)
[App]               at next (C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\fastify@4.19.2\node_modules\fastify\lib\hooks.js:185:16)
[App]               at hookRunner (C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\fastify@4.19.2\node_modules\fastify\lib\hooks.js:207:3)
[App]               at ServerResponse.onResFinished (C:\Users\matth\OneDrive\Desktop\Engineering\ForkForecast\backend\node_modules\.pnpm\fastify@4.19.2\node_modules\fastify\lib\reply.js:758:7)
[App]               at ServerResponse.emit (node:events:525:35)
[App]               at ServerResponse.emit (node:domain:489:12)
[App]               at onFinish (node:_http_outgoing:950:10)
[App]               at callback (node:internal/streams/writable:555:21)
[App]     }```

My code (mostly copied from example)

```import fp from 'fastify-plugin';
import { FastifySentry } from '@serdnam/fastify-sentry';

export default fp(async (fastify, opts) => {
  fastify.register(FastifySentry, {
    sentryOptions: {
        dsn: process.env.SENTRY_DSN,
    },
    performance: {
      hooks: [
        'onRequest',
        'preParsing',
        'preValidation',
        'preHandler',
        'preSerialization',
        'onSend'
      ],
    }
  });
});
```

If I remove all but "onRequest" there are no errors, but I'm also not seeing any performance data in the Sentry dashboard (errors work)

**Comment by MattJustMatt** [comment]
Also I had to import it like
`import { FastifySentry } from '@serdnam/fastify-sentry';`

Importing as in the readme 
import FastifySentry from '@serdnam/fastify-sentry';

Was giving me the Sentry object instead of the FastifySentry plugin

**Comment by serdnam** [comment]
Regarding the import comment, that is indeed an error in the README following recent changes I made, thanks for pointing that out! I will fix it right away.

Regarding the error, can you try registering the plugin before any other plugin? or at least before any other `"onRequest"` hooks get registered.

**Comment by serdnam** [comment]
Also you don't have to wrap this plugin with `fastify-plugin`, it is already wrapped with it.

**Comment by MattJustMatt** [comment]
Registering it before everything else and not wrapping it in fp works!! Thank you!
